#!/bin/bash

SOURCE=$(dirname "$(readlink -f "$0")")

cd -- "$SOURCE"

# Make all of the required parent dirs
find -type d -not -path "*/.git/*" -exec mkdir --parents "$HOME"/{} \;

# Make the symlinks with all of the files
find -type f -not -path "*/.git/*" -exec ln -sf -- "$SOURCE"/{} "$HOME"/{} \;

# Yes this is bad hack
rm "$HOME"/install

exit
